### ISSUE TITLE
Sprite Infos should be loaded at start. 

### ISSUE THREAD

**Issue by samsnowy** [rainybreeze777/PictureMatching#1] opened 2016-01-06 01:40 UTC
Currently in BoardController, the sprite info is loaded everytime it is needed to swap the current sprite with another. 
We should keep an array of sprites in cache and reference it everytime we need to swap.

**Comment by rainybreeze777** [comment] 2016-06-20 15:48
The enhancement in question has now been moved from BoardController.cs to BoardViewMediator.cs after the new code refactoring cd26e20.

**Comment by rainybreeze777** [comment] 2016-07-15 21:27
The issue is fixed in commit 6f9c8c1

**Closed as completed by rainybreeze777** 2016-07-15 21:27 UTC
